import type { PageEntry } from "./types.ts";

export const PAGES: PageEntry[] = [
  {
    href: "/garage-heater-calculator/methodology",
    id: "G-003",
    title: "How the planner gets 31,700 BTU/h for a 2-car garage: every formula and constant",
    h1: "Methodology",
    description: "Every formula, constant and source behind the BayHeat planner — conduction, infiltration, warm-up simulation, prices, and the BayGrade formula.",
    kind: "guide",
    layout: "report-first",
    nav: { group: "planner", label: "Methodology" },
    reviewed: null,
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 1,
  },
  {
    href: "/cost-to-heat-a-garage",
    id: "G-009",
    title: "What it costs to keep a 2-car garage at 50°F all winter, in every state",
    h1: "The Garage Heat Index",
    description: "Season cost to hold a standard attached 2-car garage at 50°F, computed for every state's population-primary station, per fuel, at current EIA prices.",
    kind: "data",
    layout: "report-first",
    primaryKeyword: "cost to heat a garage",
    reviewed: null,
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 1,
  },
  {
    href: "/garage-heater-size",
    id: "G-010",
    title: "What size heater for a 1-, 2- or 3-car garage: 7,500 to 94,300 BTU/h, depending on the walls",
    h1: "Garage heater size",
    description: "Wattage brackets for 1-, 2-, 3- and 4-car garages by insulation and climate — a planning bracket, not a load calculation.",
    kind: "guide",
    layout: "report-first",
    nav: { group: "heaters", label: "Size chart" },
    primaryKeyword: "garage heater size calculator",
    volume: 390,
    reviewed: null,
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 1,
  },
];
