import type { PageEntry } from "./types.ts";

export const PAGES: PageEntry[] = [
  {
    href: "/electric-garage-heater",
    id: "G-015",
    title: "Electric garage heaters: 1.5 kW spot heat to 10 kW, and the circuit each one needs",
    h1: "Electric garage heaters",
    description: "Every electric garage heater class from a 1.5 kW plug-in to a 10 kW ceiling unit, and the exact circuit each one needs.",
    kind: "money",
    layout: "verdict-first",
    nav: { group: "heaters", label: "Electric" },
    primaryKeyword: "garage heater electric",
    volume: 14800,
    reviewed: "electrical",
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 1,
  },
  {
    href: "/240v-garage-heater",
    id: "G-016",
    title: "240V garage heaters: 5 kW needs a 30A breaker and 10 AWG, and 4 kW won't fit a 20A circuit",
    h1: "240V garage heaters",
    description: "What a 240V garage heater actually needs: breaker size, wire gauge, GFCI, and why 4 kW doesn't fit a 20A circuit.",
    kind: "money",
    layout: "verdict-first",
    nav: { group: "heaters", label: "240V" },
    primaryKeyword: "240v garage heater",
    volume: 590,
    reviewed: "electrical",
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 1,
  },
  {
    href: "/portable-garage-heater",
    id: "G-017",
    title: "Portable garage heaters: 1,500W draws 12.5A and must be the only load on a 15A circuit",
    h1: "Portable garage heaters",
    description: "What a 15A or 20A garage receptacle can actually run, and which portable heater fits without tripping the breaker.",
    kind: "money",
    layout: "verdict-first",
    nav: { group: "heaters", label: "Portable" },
    primaryKeyword: "portable electric garage heater",
    volume: 4400,
    reviewed: "electrical",
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 1,
  },
  {
    href: "/ceiling-mount-garage-heater",
    id: "G-018",
    title: "Ceiling-mount garage heaters: 5 kW on 30A, 6 ft minimum height, 8 in from any wall",
    h1: "Ceiling-mount garage heaters",
    description: "5 kW and 7.5 kW hardwired ceiling heaters — joist load, throw, mounting height, and the clearances the manual actually requires.",
    kind: "money",
    layout: "verdict-first",
    nav: { group: "heaters", label: "Ceiling" },
    primaryKeyword: "ceiling mount garage heater",
    volume: 480,
    reviewed: "electrical",
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 1,
  },
  {
    href: "/best-wall-mount-garage-heaters",
    id: "G-019",
    title: "Wall-mount garage heaters: 1.5 kW, 5 kW and 7.5 kW, with the clearances from each manual",
    h1: "Wall-mount garage heaters",
    description: "Wall-listed electric garage heaters from a 1.5 kW infrared panel to a 7.5 kW shop unit, with nameplate and manual figures only.",
    kind: "money",
    layout: "verdict-first",
    nav: { group: "heaters", label: "Wall-mount" },
    primaryKeyword: "wall mount garage heater",
    volume: 210,
    reviewed: "electrical",
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 1,
  },
];
