import type { PageEntry } from "./types.ts";

export const PAGES: PageEntry[] = [
  {
    href: "/garage-heaters",
    id: "G-020",
    title: "Garage heaters by fuel: electric, gas, propane, diesel or heat pump, at your prices",
    h1: "Garage heaters by fuel",
    description: "Every fuel option for garage heat, compared at your own state's energy prices — not a national average.",
    kind: "money",
    layout: "verdict-first",
    nav: { group: "heaters", label: "All fuels" },
    primaryKeyword: "garage heater",
    volume: 27100,
    reviewed: null,
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-09",
    rev: 2,
  },
  {
    href: "/infrared-garage-heater",
    id: "G-021",
    title: "Infrared vs forced-air garage heaters: which one wins with the door open",
    h1: "Infrared garage heaters",
    description: "Radiant vs forced-air heat for a garage — which wins in a drafty shop, an open-door bay, or a single workbench.",
    kind: "money",
    layout: "verdict-first",
    nav: { group: "heaters", label: "Infrared" },
    primaryKeyword: "infrared garage heater",
    volume: 2400,
    reviewed: null,
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-09",
    rev: 2,
  },
  {
    href: "/diesel-heater-for-garage",
    id: "G-022",
    title: "Diesel heater for a garage: cost per hour vs electric, and the exhaust rule",
    h1: "Diesel heaters for a garage",
    description: "What a diesel air heater actually costs per hour at this week's fuel price, why the exhaust has to go outside, and when it beats electric.",
    kind: "money",
    layout: "verdict-first",
    nav: { group: "heaters", label: "Diesel" },
    primaryKeyword: "diesel heater for garage",
    volume: 6600,
    reviewed: "gas",
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-09",
    rev: 2,
  },
  {
    href: "/propane-heater-for-garage",
    id: "G-023",
    title: "Propane heaters for garages: vented vs Buddy-type, an 18-hour tank, and the CO alarm you need",
    h1: "Propane heaters for a garage",
    description: "Vented unit heaters vs portable Buddy-type radiant heaters, tank runtime, and exactly when each one is safe to run.",
    kind: "money",
    layout: "verdict-first",
    nav: { group: "heaters", label: "Propane" },
    primaryKeyword: "propane heater for garage",
    volume: 9900,
    reviewed: "gas",
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-09",
    rev: 2,
  },
  {
    href: "/electric-vs-propane-garage-heater",
    id: "G-024",
    title: "Electric vs propane vs gas vs diesel: cost per million BTU delivered at your state's prices",
    h1: "Electric vs propane garage heaters",
    description: "Electric, propane, natural gas and diesel compared on delivered cost per million BTU, computed at your own state's prices.",
    kind: "guide",
    layout: "report-first",
    nav: { group: "heaters", label: "Electric vs propane" },
    primaryKeyword: "electric vs propane garage heater",
    volume: 90,
    reviewed: "gas",
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-09",
    rev: 2,
  },
  {
    href: "/heat-pump-mini-split-for-garage",
    id: "G-025",
    title: "Mini-split heat pump for a garage: does a $2,500-7,000 install beat a $170 heater over 5 years?",
    h1: "Mini-split for a garage",
    description: "A cold-climate mini-split's 5-year cost against an electric resistance heater, including the cooling credit — and when it wins.",
    kind: "money",
    layout: "verdict-first",
    nav: { group: "heaters", label: "Mini-split" },
    primaryKeyword: "mini split for garage",
    volume: 3600,
    reviewed: "electrical",
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-09",
    rev: 2,
  },
  {
    href: "/natural-gas-garage-heater",
    id: "G-029",
    title: "Natural gas garage heater: vent it outdoors, hang it high, hire a licensed fitter",
    h1: "Natural gas garage heaters",
    description: "How to size, vent and hook up a natural gas garage heater, why a vent-free one is a no in an attached garage, and its cost per hour against electric.",
    kind: "money",
    layout: "verdict-first",
    nav: { group: "heaters", label: "Natural gas" },
    primaryKeyword: "natural gas garage heater",
    volume: 2900,
    reviewed: "gas",
    // Awaiting the human editor's sign-off (two automated fact-check rounds failed, so it escalated per
    // .claude/agents/fact-checker.md): the label says "pending" until the editor approves it.
    humanReview: "pending",
    indexable: true,
    published: "2026-10-09",
    updated: "2026-10-09",
    rev: 1,
  },
];
