import type { PageEntry } from "./types.ts";

export const PAGES: PageEntry[] = [
  {
    href: "/lab",
    id: "G-005",
    title: "The BayHeat Lab",
    h1: "The Lab",
    description: "Pre-registered tests, each with its prediction published before we measure. No claimed test without a published log.",
    kind: "lab",
    layout: "report-first",
    nav: { group: "lab", label: "The Lab" },
    reviewed: null,
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 1,
  },
  {
    href: "/lab/reports/bh-001-the-4x-problem",
    id: "G-006",
    title: "BH-001: Six publishers, seven answers, one garage (10,200-40,300 BTU/h)",
    h1: "BH-001: The 4× problem",
    description:
      "For the same 24x24 two-car garage, six publishers give BTU/h answers 10,200 to 40,300 apart. Here is why, and what our open model computes for four real envelopes.",
    kind: "lab",
    layout: "report-first",
    nav: { group: "lab", label: "BH-001" },
    reviewed: null,
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 1,
  },
  {
    href: "/lab/notebook",
    id: "G-007",
    title: "Lab notebook: every model release, price refresh and correction",
    h1: "The Lab notebook",
    description: "A dated log of every model version, price refresh and correction. We correct within 72 hours, or 24 for a safety issue.",
    kind: "lab",
    layout: "report-first",
    nav: { group: "lab", label: "Notebook" },
    reviewed: null,
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 1,
  },
];
