import type { PageEntry } from "./types.ts";

export const PAGES: PageEntry[] = [
  {
    href: "/garage-door-bottom-seal",
    id: "G-011",
    title: "Garage door bottom seals: match the retainer, close the gap, cut the draft",
    h1: "Garage door bottom seals",
    description: "T-style, bulb, J and beaded bottom seals — how to match yours to the retainer you have, and how much draft it actually cuts.",
    kind: "money",
    layout: "verdict-first",
    nav: { group: "seal", label: "Bottom seal" },
    primaryKeyword: "garage door bottom seal",
    volume: 27100,
    reviewed: null,
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 1,
  },
  {
    href: "/garage-door-weather-stripping",
    id: "G-012",
    title: "Garage door weather stripping: a $125 package cuts a 2-car garage's heat loss by 12%",
    h1: "Garage door weather stripping",
    description: "The perimeter stop seal, bottom seal and service-door kit that stop the biggest air leaks around a garage door — with the computed BTU/h it saves.",
    kind: "money",
    layout: "verdict-first",
    nav: { group: "seal", label: "Weather stripping" },
    primaryKeyword: "garage door weather stripping",
    volume: 22200,
    reviewed: null,
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 1,
  },
  {
    href: "/garage-door-insulation-kit",
    id: "G-013",
    title: "Garage door insulation kits: how much they help, and when a kit barely helps",
    h1: "Garage door insulation kits",
    description: "EPS and reflective kits for a steel garage door, what they change about your heat load, and when a bare ceiling means a kit barely helps.",
    kind: "money",
    layout: "verdict-first",
    nav: { group: "seal", label: "Door insulation kit" },
    primaryKeyword: "garage door insulation kit",
    volume: 22200,
    reviewed: null,
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 1,
  },
  {
    href: "/how-to-insulate-a-garage",
    id: "G-014",
    title: "How to insulate a garage in the order that pays back",
    h1: "How to insulate a garage",
    description: "Seal, then the door, then the ceiling — the order that pays back fastest, with a worked example: $675 of fixes cuts a 10 kW heater to 5 kW.",
    kind: "guide",
    layout: "report-first",
    nav: { group: "seal", label: "How to insulate" },
    primaryKeyword: "how to insulate a garage",
    volume: 2400,
    reviewed: null,
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 1,
  },
];
