import type { PageEntry } from "./types.ts";

export const PAGES: PageEntry[] = [
  {
    href: "/how-we-work",
    id: "G-008",
    title: "How we work: 7 pledges, how we make money, and who checks each page",
    h1: "How we work",
    description: "Seven pledges, the model behind every number, how we make money, and who checks electrical and gas claims before they publish.",
    kind: "trust",
    layout: "report-first",
    reviewed: null,
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 1,
  },
  {
    href: "/about",
    id: "G-026",
    title: "About BayHeat: an open garage-climate model, a lab, and the people who check it",
    h1: "About BayHeat",
    description: "Who publishes BayHeat, how the model works, and how to reach Laqaer Products.",
    kind: "legal",
    layout: "report-first",
    reviewed: null,
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 2,
  },
  {
    href: "/privacy",
    id: "G-027",
    title: "Privacy: what BayHeat collects (almost nothing) and why",
    h1: "Privacy policy",
    description: "What BayHeat collects, what it doesn't, and how email, analytics and the planner's saved-garage feature work.",
    kind: "legal",
    layout: "report-first",
    reviewed: null,
    indexable: true,
    published: "2026-10-02",
    updated: "2026-10-02",
    rev: 2,
  },
];
