import type { Product } from "../types.ts";

// Insulate-first measures (planner-engineering.md §15): the cheapest, fastest-payback fixes, and the
// commercial core of the fix-first card. Door width/height decide which kit fits; the planner picks the right
// productId by garage door size, not the reader.

export const PRODUCTS: Product[] = [
  {
    id: "seal-bottom-t-8ft",
    name: "Garage door bottom seal, T-style rubber, 8 ft (1-car door)",
    kind: "seal_bottom",
    searchQuery: "garage door bottom seal T style rubber 8 ft",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "seal-bottom-t-16ft",
    name: "Garage door bottom seal, T-style rubber, 16 ft (2-car door)",
    kind: "seal_bottom",
    searchQuery: "garage door bottom seal T style rubber 16 ft",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "seal-bottom-bulb-16ft",
    name: "Garage door bottom seal, bulb-style, 16 ft",
    kind: "seal_bottom",
    searchQuery: "garage door bottom seal bulb style 16 ft",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "seal-retainer-kit",
    name: "Garage door bottom seal aluminum retainer track kit",
    kind: "seal_retainer",
    searchQuery: "garage door bottom seal retainer track kit",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "seal-perimeter-stop",
    name: "Garage door perimeter weatherstrip / stop seal kit",
    kind: "seal_perimeter",
    searchQuery: "garage door perimeter weatherstrip stop seal kit",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "seal-service-door-kit",
    name: "Service door weatherstrip kit (jambs + sweep)",
    kind: "seal_service_door",
    searchQuery: "exterior door weatherstrip kit jambs sweep",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "attic-hatch-gasket",
    name: "Attic access hatch weatherstrip gasket kit",
    kind: "attic_hatch",
    searchQuery: "attic access hatch weatherstrip gasket kit",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "door-kit-eps-matador",
    name: "Matador EPS garage door insulation kit (fits most 16x7 doors)",
    kind: "door_kit_eps",
    searchQuery: "Matador garage door insulation kit EPS 16x7",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "door-kit-eps-cellofoam",
    name: "Cellofoam EPS garage door insulation kit (fits most 16x7 doors)",
    kind: "door_kit_eps",
    searchQuery: "Cellofoam garage door insulation kit EPS 16x7",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "door-kit-reflective-owens-corning",
    name: "Owens Corning reflective garage door insulation kit",
    kind: "door_kit_reflective",
    searchQuery: "Owens Corning reflective garage door insulation kit",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "door-kit-reflective-reach-barrier",
    name: "Reach Barrier reflective garage door insulation kit",
    kind: "door_kit_reflective",
    searchQuery: "Reach Barrier reflective garage door insulation kit",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
];
