import type { Product } from "../types.ts";

// Insulate-first measures (planner-engineering.md §15): the cheapest, fastest-payback fixes, and the
// commercial core of the fix-first card. Door width/height decide which kit fits; the planner picks the right
// productId by garage door size, not the reader.

export const PRODUCTS: Product[] = [
  {
    id: "seal-bottom-t-8ft",
    name: "Garage door bottom seal, 1/4 in T-style, for an 8 ft (1-car) door",
    kind: "seal_bottom",
    asin: "B07P43LTYH",
    searchQuery: "garage door bottom seal T style rubber 8 ft",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "seal-bottom-t-16ft",
    name: "Garage door bottom seal, 1/4 in T-style, for a 16 ft (2-car) door",
    kind: "seal_bottom",
    asin: "B07P55PSW1",
    searchQuery: "garage door bottom seal T style rubber 16 ft",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "seal-bottom-bulb-16ft",
    name: "Garage door bottom seal, small P-bulb style, 16.5 ft",
    kind: "seal_bottom",
    asin: "B0C9952GSX",
    searchQuery: "garage door bottom seal bulb style 16 ft",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "seal-retainer-kit",
    name: "Garage door bottom seal with aluminum retainer track, 16 ft",
    kind: "seal_retainer",
    asin: "B0D9Y1NWCT",
    searchQuery: "garage door bottom seal retainer track kit",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "seal-perimeter-stop",
    name: "M-D garage door top and side seal, 30 ft",
    kind: "seal_perimeter",
    asin: "B0009F86SE",
    searchQuery: "garage door perimeter weatherstrip stop seal kit",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "seal-service-door-kit",
    name: "Service door weatherstrip kit (jambs + sweep)",
    kind: "seal_service_door",
    searchQuery: "exterior door weatherstrip kit jambs sweep",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "attic-hatch-gasket",
    name: "Attic access hatch weatherstrip (EPDM self-stick tape, 10 ft)",
    kind: "attic_hatch",
    asin: "B00012FQCY",
    searchQuery: "attic access hatch weatherstrip gasket kit",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "door-kit-eps-matador",
    name: "Matador EPS garage door insulation kit (fits most 16x7 doors)",
    kind: "door_kit_eps",
    searchQuery: "Matador garage door insulation kit EPS 16x7",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "door-kit-eps-cellofoam",
    name: "Cellofoam EPS garage door insulation kit (fits most 16x7 doors)",
    kind: "door_kit_eps",
    searchQuery: "Cellofoam garage door insulation kit EPS 16x7",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "door-kit-reflective-owens-corning",
    name: "Owens Corning reflective garage door insulation kit",
    kind: "door_kit_reflective",
    searchQuery: "Owens Corning reflective garage door insulation kit",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
  {
    id: "door-kit-reflective-reach-barrier",
    name: "Reach Barrier reflective garage door insulation kit, 8x8 single-door size, pack of 2 (covers a 16 ft door)",
    kind: "door_kit_reflective",
    asin: "B0HG41WQG3",
    searchQuery: "Reach Barrier reflective garage door insulation kit",
    partnerUrls: {},
    priceClass: "$",
    priceClassChecked: "2026-09-25",
    specFactIds: [],
  },
];
