#!/usr/bin/env node
/**
 * Writes out/_redirects and out/_headers after `next build`, for Cloudflare Workers static assets.
 *
 *   npm run build            # next build && node scripts/cloudflare-routing.mjs
 *
 * A static export can't carry next.config.ts redirects() or headers(), so this script owns both:
 * - redirects: lib/redirects.ts (permanent, 308 like Next's `permanent: true`), plus the old /r/<code> report
 *   permalink, which now opens the same report in the planner (302: the planner URL is the canonical home).
 * - headers: the security headers the Vercel deploy sent, the /embed/* framing exception, long caching for
 *   Next's hashed /_next/static files, and image/png for the two extensionless metadata images.
 *
 * Syntax: https://developers.cloudflare.com/workers/static-assets/redirects/ and .../headers/
 */
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { REDIRECTS } from "../lib/redirects.ts";

export const OUT = "out";

export function redirectsFile(rules = REDIRECTS) {
  const lines = [
    "# Generated by scripts/cloudflare-routing.mjs from lib/redirects.ts. Do not edit by hand.",
    // Next stripped a trailing slash before matching; static-assets redirects match the path exactly.
    ...rules.flatMap((r) => [`${r.source} ${r.destination} 308`, `${r.source}/ ${r.destination} 308`]),
    "/r/:code /garage-heater-calculator?g=:code 302",
    // Vercel answered /page/ with a 308 to /page; the assets router's own trailing-slash fix is a 307. Keep the
    // permanent redirect (the deepest content path today is three segments: /lab/reports/<slug>).
    "/:a/ /:a 308",
    "/:a/:b/ /:a/:b 308",
    "/:a/:b/:c/ /:a/:b/:c 308",
  ];
  return `${lines.join("\n")}\n`;
}

const SECURITY = [
  "X-Content-Type-Options: nosniff",
  "Referrer-Policy: strict-origin-when-cross-origin",
  "Permissions-Policy: camera=(), microphone=(), geolocation=()",
];

export function headersFile() {
  const block = (path, headers) => [path, ...headers.map((h) => `  ${h}`)].join("\n");
  return `${[
    "# Generated by scripts/cloudflare-routing.mjs. Do not edit by hand.",
    block("/*", [...SECURITY, "X-Frame-Options: SAMEORIGIN"]),
    // The embeddable widgets must load in other sites' iframes.
    block("/embed/*", ["! X-Frame-Options", "Content-Security-Policy: frame-ancestors *"]),
    // Content-hashed file names: safe to cache for a year.
    block("/_next/static/*", ["Cache-Control: public, max-age=31536000, immutable"]),
    // app/opengraph-image.tsx and app/apple-icon.tsx export to files with no extension.
    block("/opengraph-image", ["Content-Type: image/png"]),
    block("/apple-icon", ["Content-Type: image/png"]),
  ].join("\n")}\n`;
}

function main() {
  if (!existsSync(join(OUT, "index.html"))) {
    process.stderr.write(`cloudflare-routing: ${OUT}/index.html not found; run next build first\n`);
    process.exit(1);
  }
  writeFileSync(join(OUT, "_redirects"), redirectsFile());
  writeFileSync(join(OUT, "_headers"), headersFile());
  process.stdout.write(`cloudflare-routing: wrote ${OUT}/_redirects (${redirectsFile().trim().split("\n").length - 1} rules) and ${OUT}/_headers\n`);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
